export interface ReceivedBazaraData {
    banksReceived?: boolean,
    visitorPeopleReceived?: boolean,
    peopleReceived?: boolean,
    personAddressesReceived?: boolean,
    productsReceived?: boolean,
    productDetailsReceived?: boolean,
    productDetailStoreAssetsReceived?: boolean,
    ordersReceived?: boolean,
    orderDetailsReceived?: boolean,
    productCategoriesReceived?: boolean,
    photoGalleriesReceived?: boolean,
    picturesReceived?: boolean,
    visitorProductsReceived?: boolean,
    ordersSent?: boolean,
    orderDetailsSent?: boolean,
    missionsReceived?: boolean,
    missionDetailsReceived?: boolean,
    propertyDescriptionsReceived?: boolean,
    settingReceived?: boolean,
    extraDataReceived?: boolean,
    promotionReceived?: boolean,
    promotionDetailReceived?: boolean,
    promotionEntityReceived?: boolean,
}