export enum StoreName {
    Login = 'Login',
    Bank = 'Bank',
    Product = 'Product',
    VisitorProduct = 'VisitorProduct',
    ProductDetail = 'ProductDetail',
    ProductCategory = 'ProductCategory',
    Person = 'Person',
    VisitorPerson = 'VisitorPerson',
    PersonAddress = 'PersonAddress',
    Cash = 'Cash',
    CheckList = 'CheckList',
    Cheque = 'Cheque',
    CompanyInfo = 'CompanyInfo',
    CostLevelName = 'CostLevelName',
    ExtraData = 'ExtraData',
    Income = 'Income',
    IncomeGroup = 'IncomeGroup',
    Mission = 'Mission',
    MissionDetail = 'MissionDetail',
    Order = 'Order',
    OrderDetail = 'OrderDetail',
    Picture = 'Picture',
    PhotoGallery = 'PhotoGallery',
    ProductDetailStoreAsset = 'ProductDetailStoreAsset',
    PropertyDescription = 'PropertyDescription',
    Setting = 'Setting'
}